-- Terra — demo seed. Generated by tools/build_seed.mjs; do not edit by hand.
--
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query →
-- paste → Run), the same way the schema migration was applied. The editor
-- runs as a privileged role, which is what makes it able to write `needs`:
-- that table deliberately has no insert policy, so neither the anon key nor
-- a signed-in user can add rows. Only the service role and the SQL editor.
--
-- Safe to re-run. Everything below is owned by one fixed demo user, and the
-- script clears that user's rows before inserting, so you get the same 32
-- ministries and 65 needs every time rather than a second copy of them.
--
-- ALL OF THIS DATA IS FICTIONAL. Every organisation, person and need is
-- invented, and every contact address is on example.org, which cannot
-- receive mail. To remove it again:
--
--   delete from auth.users where id = '00000000-0000-4000-8000-00000000d3m0';
--
-- which cascades to the profile, the ministries and their needs.

begin;

-- ---------------------------------------------------------- demo owner
--
-- ministries.owner_id is not null and references profiles(id), which
-- references auth.users(id) — so the seed needs a user to hang off. It has
-- no password at all: the column is nullable (OAuth users carry none), and a
-- null there means no credential can ever match, which is what you want of
-- an account that exists only to own rows. Writing a hash instead would have
-- pulled in pgcrypto's crypt() for no benefit. The on_auth_user_created
-- trigger writes the matching profile.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  created_at, updated_at, raw_app_meta_data, raw_user_meta_data,
  confirmation_token, recovery_token, email_change_token_new, email_change
)
values (
  '00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-00000000d3m0', 'authenticated', 'authenticated',
  'demo@example.org', null, now(),
  now(), now(), '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Terra demo data","role":"ministry"}'::jsonb,
  '', '', '', ''
)
on conflict (id) do nothing;

-- The trigger covers a fresh insert; this covers a database where the user
-- already exists but the profile was removed.
insert into public.profiles (id, full_name, role)
values ('00000000-0000-4000-8000-00000000d3m0', 'Terra demo data', 'ministry')
on conflict (id) do update set role = 'ministry';

-- Clear this owner's previous seed. Needs cascade from ministries.
delete from public.ministries where owner_id = '00000000-0000-4000-8000-00000000d3m0';

-- ---------------------------------------------------------- ministries
insert into public.ministries
  (owner_id, slug, name, city, country, lat, lon, region, focus, since, staff, languages, contact, blurb)
values
  ('00000000-0000-4000-8000-00000000d3m0', 'ulaanbaatar-ger', 'Ulaanbaatar Ger Districts Trust', 'Ulaanbaatar', 'Mongolia', 47.9186, 106.9177, 'asia', array['shelter', 'children']::text[], 2011, 9, array['Mongolian', 'Russian']::text[], 'hello@ulaanbaatar-ger.example.org', 'Works through the winter in the unserviced ger districts on the city''s northern slopes, where families heat single-room tents with raw coal.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'aleppo-neighbours', 'Aleppo Neighbours Initiative', 'Aleppo', 'Syria', 36.2021, 37.1343, 'mena', array['shelter', 'trauma']::text[], 2017, 14, array['Arabic', 'English']::text[], 'salaam@aleppo-neighbours.example.org', 'Neighbourhood committees clearing and re-roofing damaged buildings street by street, starting with the households that never left.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'cairo-garbage-city', 'Cairo Garbage City Hope', 'Cairo', 'Egypt', 30.0444, 31.2357, 'mena', array['health', 'work']::text[], 2006, 22, array['Arabic', 'English']::text[], 'office@cairo-hope.example.org', 'Walks with the Zabbaleen recycling families of Manshiyat Naser: clinic days, school fees, and safer ways to do the sorting work.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'nairobi-mathare', 'Mathare Hope Collective', 'Nairobi', 'Kenya', -1.2864, 36.8172, 'africa', array['children', 'health', 'translation']::text[], 2009, 18, array['Swahili', 'English', 'Kikuyu']::text[], 'karibu@mathare-hope.example.org', 'A church-run centre in the Mathare valley: after-school classes, a two-room clinic, and a Swahili study group that writes its own material.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'karachi-dockside', 'Karachi Dockside Mission', 'Karachi', 'Pakistan', 24.8607, 67.0011, 'asia', array['work', 'education']::text[], 2014, 11, array['Urdu', 'Sindhi', 'English']::text[], 'contact@karachi-dockside.example.org', 'Among the fishing families of Ibrahim Hyderi — boat safety, school enrolment, and literacy classes held between tides.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'amman-welcome', 'Amman Refugee Welcome', 'Amman', 'Jordan', 31.9454, 35.9284, 'mena', array['refugees', 'trauma']::text[], 2013, 26, array['Arabic', 'English']::text[], 'welcome@amman-welcome.example.org', 'First-week accompaniment for newly arrived families: paperwork, a mattress, and someone who speaks both languages in the room.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kyiv-winter', 'Kyiv Winter Response', 'Kyiv', 'Ukraine', 50.4501, 30.5234, 'europe', array['shelter', 'food']::text[], 2022, 31, array['Ukrainian', 'Russian', 'English']::text[], 'shtab@kyiv-winter.example.org', 'Keeps heat and light in apartment blocks through the cold months: generators, boiler repairs, and a hot meal round at street level.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'warsaw-hosts', 'Warsaw Border Hosts', 'Warsaw', 'Poland', 52.2297, 21.0122, 'europe', array['refugees']::text[], 2022, 8, array['Polish', 'Ukrainian', 'English']::text[], 'dom@warsaw-hosts.example.org', 'Matches arriving families with host households, then stays alongside both for the first hundred days.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'london-estates', 'London Estates Fellowship', 'London', 'United Kingdom', 51.5072, -0.1276, 'europe', array['children', 'food']::text[], 1998, 12, array['English', 'Bengali', 'Somali']::text[], 'hello@london-estates.example.org', 'Youth clubs and a food round on three east London estates, run by people who grew up on them.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'madrid-puente', 'Madrid Puente Comunidad', 'Madrid', 'Spain', 40.4168, -3.7038, 'europe', array['education', 'work']::text[], 2015, 7, array['Spanish', 'Arabic', 'English']::text[], 'hola@madrid-puente.example.org', 'Spanish classes and first-job coaching in Usera, for people who arrived with qualifications nobody here will read.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'lima-pueblos', 'Lima Pueblos Jóvenes', 'Lima', 'Peru', -12.0464, -77.0428, 'latam', array['water', 'children']::text[], 2008, 15, array['Spanish', 'Quechua']::text[], 'hola@lima-pueblos.example.org', 'On the sand hills above the city, where water arrives by truck: tanks, taps, and a children''s programme that runs all summer.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bogota-casa', 'Bogotá Casa Abierta', 'Bogotá', 'Colombia', 4.711, -74.0721, 'latam', array['refugees', 'trauma']::text[], 2018, 19, array['Spanish', 'English']::text[], 'casa@bogota-abierta.example.org', 'A day house for Venezuelan families still on the move: casework, a play room, and somewhere to leave a bag.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'saopaulo-luz', 'São Paulo Favela Luz', 'São Paulo', 'Brazil', -23.5505, -46.6333, 'latam', array['children', 'discipleship']::text[], 2004, 21, array['Portuguese']::text[], 'oi@favela-luz.example.org', 'A music school and small-group network in Brasilândia, with instruments that go home with the students.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'santiago-manos', 'Santiago Manos Abiertas', 'Santiago', 'Chile', -33.4489, -70.6693, 'latam', array['food', 'shelter']::text[], 2012, 6, array['Spanish', 'Haitian Creole']::text[], 'manos@santiago-abiertas.example.org', 'Night rounds through the centre in winter: soup, blankets, and the slow work of getting someone indoors.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'dhaka-riverside', 'Dhaka Riverside Trust', 'Dhaka', 'Bangladesh', 23.8103, 90.4125, 'asia', array['shelter', 'education']::text[], 2010, 24, array['Bengali', 'English']::text[], 'trust@dhaka-riverside.example.org', 'Builds and rebuilds along the Buriganga for families who move every flood season, and teaches their children to read.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kolkata-sealdah', 'Kolkata Sealdah Care', 'Kolkata', 'India', 22.5726, 88.3639, 'asia', array['children', 'health']::text[], 1996, 29, array['Bengali', 'Hindi', 'English']::text[], 'care@sealdah.example.org', 'Meets children arriving alone on the night trains into Sealdah station, and keeps meeting them until there is somewhere to go.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'mumbai-dharavi', 'Mumbai Dharavi Neighbours', 'Mumbai', 'India', 19.076, 72.8777, 'asia', array['work']::text[], 2007, 13, array['Marathi', 'Hindi', 'English']::text[], 'hello@dharavi-neighbours.example.org', 'Tailoring and leatherwork training inside Dharavi, run with the workshops rather than around them.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'chennai-coastal', 'Chennai Coastal Hope', 'Chennai', 'India', 13.0827, 80.2707, 'asia', array['shelter', 'translation']::text[], 2005, 16, array['Tamil', 'English']::text[], 'hope@chennai-coastal.example.org', 'Cyclone-season preparation in the fishing settlements north of the harbour, plus a Tamil translation desk.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bengaluru-migrant', 'Bengaluru Migrant Welcome', 'Bengaluru', 'India', 12.9716, 77.5946, 'asia', array['refugees', 'work']::text[], 2016, 10, array['Kannada', 'Hindi', 'English']::text[], 'namaskara@blr-welcome.example.org', 'For construction-site families who arrive from three states away: wage disputes, school places, and a language bridge.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kathmandu-hillside', 'Kathmandu Hillside Trust', 'Kathmandu', 'Nepal', 27.7172, 85.324, 'asia', array['shelter', 'children']::text[], 2015, 12, array['Nepali', 'English']::text[], 'namaste@kathmandu-hillside.example.org', 'Rebuilds on unstable ground above the valley, and runs a youth programme for the families waiting on it.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'manila-estero', 'Manila Estero Fellowship', 'Manila', 'Philippines', 14.5995, 120.9842, 'asia', array['water', 'food']::text[], 2003, 17, array['Filipino', 'English']::text[], 'kumusta@manila-estero.example.org', 'Along the esteros of Tondo: creek clean-ups, a feeding programme, and a fight for drainage that actually drains.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'jakarta-kampung', 'Jakarta Kampung Bright', 'Jakarta', 'Indonesia', -6.2088, 106.8456, 'asia', array['shelter', 'education']::text[], 2013, 14, array['Indonesian', 'Javanese']::text[], 'salam@kampung-bright.example.org', 'Fire safety and literacy in the dense kampungs of North Jakarta, where one cooking fire takes forty homes.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bangkok-klongtoey', 'Bangkok Klong Toey Friends', 'Bangkok', 'Thailand', 13.7563, 100.5018, 'asia', array['prison', 'discipleship']::text[], 2001, 9, array['Thai', 'English']::text[], 'sawasdee@klongtoey-friends.example.org', 'Prison visiting and aftercare around the port district: the first month out is the one that decides the rest.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'phnompenh-riverside', 'Phnom Penh Riverside Care', 'Phnom Penh', 'Cambodia', 11.5564, 104.9282, 'asia', array['education', 'work']::text[], 2011, 11, array['Khmer', 'English']::text[], 'suosdey@pp-riverside.example.org', 'Evening classes and small loans for families along the riverfront, most of them one eviction from starting again.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'lagos-makoko', 'Lagos Makoko Waterline', 'Lagos', 'Nigeria', 6.5244, 3.3792, 'africa', array['education', 'shelter']::text[], 2012, 13, array['Yoruba', 'English', 'Egun']::text[], 'hello@makoko-waterline.example.org', 'A school on stilts over the lagoon, rebuilt by the community''s own carpenters roughly every four years.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'dakar-medina', 'Dakar Médina Espoir', 'Dakar', 'Senegal', 14.7167, -17.4677, 'africa', array['translation', 'children']::text[], 2010, 8, array['Wolof', 'French']::text[], 'bonjour@medina-espoir.example.org', 'A Wolof translation circle and a girls'' football league, both of which fill the same courtyard on different evenings.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kinshasa-ngaliema', 'Kinshasa Ngaliema Mission', 'Kinshasa', 'DR Congo', -4.4419, 15.2663, 'africa', array['water', 'health']::text[], 1999, 20, array['French', 'Lingala']::text[], 'bonjour@ngaliema-mission.example.org', 'Boreholes and a nurse-training room on the western edge of the city, where the piped supply stops.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'addis-merkato', 'Addis Merkato Care', 'Addis Ababa', 'Ethiopia', 9.032, 38.7469, 'africa', array['work', 'translation']::text[], 2008, 15, array['Amharic', 'Oromo', 'English']::text[], 'selam@merkato-care.example.org', 'Savings groups among Merkato''s street traders, and an Amharic audio recording room for people who do not read.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'capetown-khayelitsha', 'Khayelitsha Light', 'Cape Town', 'South Africa', -33.9249, 18.4241, 'africa', array['prison', 'trauma']::text[], 2006, 17, array['Xhosa', 'Afrikaans', 'English']::text[], 'molo@khayelitsha-light.example.org', 'Gang-exit mentoring and trauma debriefs, run by people the young men will actually listen to.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'beirut-karantina', 'Beirut Karantina Rebuild', 'Beirut', 'Lebanon', 33.8938, 35.5018, 'mena', array['shelter']::text[], 2020, 10, array['Arabic', 'French', 'English']::text[], 'ahla@karantina-rebuild.example.org', 'Still finishing the windows and roofs the port blast took out, household by household, in the quarter closest to it.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bishkek-novostroyka', 'Bishkek Novostroyka Trust', 'Bishkek', 'Kyrgyzstan', 42.8746, 74.5698, 'asia', array['children', 'shelter']::text[], 2014, 7, array['Kyrgyz', 'Russian']::text[], 'salam@bishkek-trust.example.org', 'In the unplanned novostroyka settlements at the city edge: a youth room, and coal before the first hard frost.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'toronto-newcomer', 'Toronto Newcomer Table', 'Toronto', 'Canada', 43.6532, -79.3832, 'northam', array['refugees']::text[], 2017, 6, array['English', 'French', 'Tigrinya', 'Dari']::text[], 'welcome@newcomer-table.example.org', 'A weekly table in Scarborough where claimants, hosts and a volunteer lawyer end up at the same meal.')
on conflict (slug) do update set
  owner_id = excluded.owner_id, name = excluded.name, city = excluded.city,
  country = excluded.country, lat = excluded.lat, lon = excluded.lon,
  region = excluded.region, focus = excluded.focus, since = excluded.since,
  staff = excluded.staff, languages = excluded.languages,
  contact = excluded.contact, blurb = excluded.blurb;

-- --------------------------------------------------------------- needs
--
-- status 'live' explicitly: the column defaults to pending_review so that
-- anything reaching the table without passing moderation stays invisible,
-- and only live rows are readable by the public policy. Seed data has no
-- moderation pass to go through, so it is marked live here.
--
-- Joined on slug rather than carrying ministry uuids, so the ids stay
-- whatever Postgres generated and this file has no machine state in it.
insert into public.needs
  (ministry_id, title, type, urgency, people, focus, remote, commitment, skills, detail, posted, status)
select m.id, 'Winter appeal campaign design', 'expertise', 'soon', 1, 'shelter', true, '10 hrs total · 3 weeks', array['Graphic design', 'Canva or Figma']::text[], 'A set of social posts, a one-page flyer and an email header for our winter insulation appeal. We supply the photos and the words; we need them to look like one campaign.', '2026-08-29'::date, 'live' from public.ministries m where m.slug = 'ulaanbaatar-ger'
union all
select m.id, 'Winter night shelter volunteers', 'volunteers', 'urgent', 4, 'shelter', false, '2 nights/week · Dec–Mar', array['Mongolian', 'First aid']::text[], 'Two people a night on a rota with our staff, from December through March. Training and a bed in the building are provided.', '2026-08-21'::date, 'live' from public.ministries m where m.slug = 'ulaanbaatar-ger'
union all
select m.id, 'Structural engineer (remote review)', 'expertise', 'urgent', 1, 'shelter', true, '4 hrs/week · 2 months', array['Structural engineering', 'Arabic helpful']::text[], 'Reviewing photographs, measurements and sketches of damaged load-bearing walls, and telling the committee which buildings can be reoccupied. Fully remote, on our timetable.', '2026-09-01'::date, 'live' from public.ministries m where m.slug = 'aleppo-neighbours'
union all
select m.id, 'Grant application writer', 'expertise', 'soon', 1, 'shelter', true, '15 hrs · one application', array['Grant writing', 'English']::text[], 'Turn our re-roofing reports into a strong application for a foundation deadline in November. We have the budget and the photos; we need someone who has written these before.', '2026-08-11'::date, 'live' from public.ministries m where m.slug = 'aleppo-neighbours'
union all
select m.id, 'Occupational health advisor', 'expertise', 'urgent', 1, 'health', true, '3 hrs/week · 2 months', array['Occupational health', 'Arabic helpful']::text[], 'Help us write sorting-line safety guidance the families will actually use, and coach four of our staff by video to teach it.', '2026-08-30'::date, 'live' from public.ministries m where m.slug = 'cairo-garbage-city'
union all
select m.id, 'Bookkeeping set-up for a recycling co-op', 'expertise', 'soon', 1, 'work', true, '8 hrs total', array['Bookkeeping', 'Spreadsheets', 'Arabic helpful']::text[], 'A simple, honest set of books for a twelve-family sorting co-operative: a spreadsheet template, a monthly routine, and one video call to walk the treasurer through it.', '2026-07-30'::date, 'live' from public.ministries m where m.slug = 'cairo-garbage-city'
union all
select m.id, 'Swahili Bible study reviewers', 'volunteers', 'soon', 3, 'translation', true, '3 hrs/week · 2 months', array['Swahili', 'Theology']::text[], 'We write our own study material and need first-language Swahili readers with some theological training to check it before it goes to print. Shared documents, comments by email.', '2026-08-18'::date, 'live' from public.ministries m where m.slug = 'nairobi-mathare'
union all
select m.id, 'Clinic nurse (3 months)', 'volunteers', 'urgent', 1, 'health', false, 'full time · 3 months', array['Nursing', 'Kenyan registration']::text[], 'One registered nurse to hold the clinic''s morning list while our own staff complete their midwifery training.', '2026-08-26'::date, 'live' from public.ministries m where m.slug = 'nairobi-mathare'
union all
select m.id, 'Website refresh', 'expertise', 'soon', 1, 'children', true, '20 hrs total · 6 weeks', array['Web design', 'WordPress or Squarespace']::text[], 'Our site is six years old and does not work on a phone, which is where every parent and donor sees it. Five pages, our content, and a donate button that works.', '2026-08-04'::date, 'live' from public.ministries m where m.slug = 'nairobi-mathare'
union all
select m.id, 'Boat-safety course materials', 'expertise', 'soon', 1, 'work', true, '10 hrs total', array['Instructional design', 'Urdu helpful']::text[], 'Turn our boat-safety checklist into a picture-led handout and a short slide deck our own staff can teach from on the dock. Most of the crew do not read.', '2026-08-14'::date, 'live' from public.ministries m where m.slug = 'karachi-dockside'
union all
select m.id, 'School exercise books', 'supplies', 'ongoing', 0, 'education', false, 'termly', '{}', 'Standing need: exercise books and pencils for around two hundred children each term.', '2026-06-19'::date, 'live' from public.ministries m where m.slug = 'karachi-dockside'
union all
select m.id, 'Arabic-English interpreters (phone)', 'volunteers', 'urgent', 4, 'refugees', true, '2 hrs/week · on call', array['Arabic', 'English']::text[], 'Joining registration and medical appointments by phone or video when a family has no one in the room who speaks both languages. The thing we are most short of.', '2026-08-31'::date, 'live' from public.ministries m where m.slug = 'amman-welcome'
union all
select m.id, 'Trauma counselling supervision', 'expertise', 'soon', 1, 'trauma', true, '2 hrs/fortnight · 6 months', array['Clinical supervision', 'Trauma']::text[], 'Video supervision for six caseworkers carrying heavy stories with no one above them to take it to.', '2026-08-09'::date, 'live' from public.ministries m where m.slug = 'amman-welcome'
union all
select m.id, 'Generators and fuel', 'supplies', 'urgent', 0, 'shelter', false, 'before first frost', '{}', 'Portable generators and diesel for twelve apartment blocks, so lifts, pumps and a warm room keep running through the outages.', '2026-09-02'::date, 'live' from public.ministries m where m.slug = 'kyiv-winter'
union all
select m.id, 'Donor newsletter writer', 'expertise', 'soon', 1, 'shelter', true, '4 hrs/month', array['Copywriting', 'Email marketing']::text[], 'A monthly email to our supporters. We send notes, photos and numbers; you turn them into something people open and read.', '2026-08-25'::date, 'live' from public.ministries m where m.slug = 'kyiv-winter'
union all
select m.id, 'Host-matching database set-up', 'expertise', 'soon', 1, 'refugees', true, '15 hrs · 1 month', array['Airtable or Notion', 'Data']::text[], 'We match families with hosts from three spreadsheets and a WhatsApp group. Build us one simple base with sign-up forms, and train two coordinators to run it.', '2026-08-07'::date, 'live' from public.ministries m where m.slug = 'warsaw-hosts'
union all
select m.id, 'Legal aid partner', 'partners', 'ongoing', 0, 'refugees', true, 'standing referral', array['Immigration law']::text[], 'A firm or legal clinic that will take referrals for residence and work-permit questions, by video.', '2026-05-22'::date, 'live' from public.ministries m where m.slug = 'warsaw-hosts'
union all
select m.id, 'Youth club mentors', 'volunteers', 'soon', 4, 'children', false, '1 evening/week · 1 year', array['Youth work', 'DBS check']::text[], 'Turning up, week after week, for the same group of teenagers. Consistency matters more to us than experience.', '2026-08-16'::date, 'live' from public.ministries m where m.slug = 'london-estates'
union all
select m.id, 'Food round drivers', 'volunteers', 'ongoing', 2, 'food', false, '1 morning/week', array['Driving licence']::text[], 'Collecting from two supermarkets and dropping off across three estates. Van provided.', '2026-07-11'::date, 'live' from public.ministries m where m.slug = 'london-estates'
union all
select m.id, 'Spanish conversation partners (video)', 'volunteers', 'soon', 5, 'education', true, '1 hr/week · 3 months', array['Spanish', 'Patience']::text[], 'Half-hour video calls with adult learners who have finished the classroom course and need to practise before job interviews.', '2026-08-12'::date, 'live' from public.ministries m where m.slug = 'madrid-puente'
union all
select m.id, 'CV and LinkedIn reviewers', 'volunteers', 'ongoing', 3, 'work', true, '2 hrs/month', array['Recruitment or HR', 'Spanish']::text[], 'Reviewing CVs and LinkedIn profiles for engineers, nurses and teachers whose qualifications are real but written for another country.', '2026-06-28'::date, 'live' from public.ministries m where m.slug = 'madrid-puente'
union all
select m.id, 'Water tanks', 'supplies', 'urgent', 0, 'water', false, '18 tanks', '{}', 'Eighteen 1,100-litre tanks for homes on the upper slopes, where the truck comes twice a week and there is nowhere to keep what it brings.', '2026-08-28'::date, 'live' from public.ministries m where m.slug = 'lima-pueblos'
union all
select m.id, 'Summer club curriculum', 'expertise', 'soon', 1, 'children', true, '12 hrs total', array['Curriculum design', 'Spanish']::text[], 'Six weeks of children''s club sessions written up so any of our volunteers can lead them: a game, a story and a take-home activity for each.', '2026-08-02'::date, 'live' from public.ministries m where m.slug = 'lima-pueblos'
union all
select m.id, 'Family caseworkers', 'volunteers', 'urgent', 2, 'refugees', false, '3 days/week · 3 months', array['Spanish', 'Casework']::text[], 'Sitting with Venezuelan families at the day house to work through documents, school places and next steps.', '2026-08-27'::date, 'live' from public.ministries m where m.slug = 'bogota-casa'
union all
select m.id, 'Case-management system advice', 'expertise', 'soon', 1, 'refugees', true, '6 hrs total', array['Nonprofit CRM', 'Data protection']::text[], 'We track four hundred families on paper. Help us choose a simple, secure case-management tool and set up the first version.', '2026-08-06'::date, 'live' from public.ministries m where m.slug = 'bogota-casa'
union all
select m.id, 'Music school instruments', 'supplies', 'ongoing', 0, 'children', false, 'rolling', '{}', 'Violins, guitars and keyboards in playable condition. They go home with the students, so they wear out.', '2026-07-03'::date, 'live' from public.ministries m where m.slug = 'saopaulo-luz'
union all
select m.id, 'Concert video editor', 'expertise', 'soon', 1, 'children', true, '5 hrs/month', array['Video editing', 'Portuguese helpful']::text[], 'Our students film their concerts on phones. Turn the footage into short videos for families and supporters each month.', '2026-08-19'::date, 'live' from public.ministries m where m.slug = 'saopaulo-luz'
union all
select m.id, 'Night outreach team', 'volunteers', 'ongoing', 4, 'food', false, '1 night/week · Jun–Sep', array['Spanish']::text[], 'Walking the winter night round in pairs with soup and blankets, alongside one of our staff.', '2026-06-14'::date, 'live' from public.ministries m where m.slug = 'santiago-manos'
union all
select m.id, 'Winter blankets', 'supplies', 'soon', 0, 'shelter', false, '200 blankets', '{}', 'Warm, washable blankets for the night round. We hand out around fifty a week through July.', '2026-08-05'::date, 'live' from public.ministries m where m.slug = 'santiago-manos'
union all
select m.id, 'Flood-resilient housing designer', 'expertise', 'urgent', 1, 'shelter', true, '6 hrs/week · 3 months', array['Architecture', 'Flood engineering']::text[], 'Drawing a raised, re-buildable house our local builders can put up for under a set budget. We send site photos and measurements; you send drawings.', '2026-08-24'::date, 'live' from public.ministries m where m.slug = 'dhaka-riverside'
union all
select m.id, 'Bengali reading exercises', 'volunteers', 'soon', 3, 'education', true, '3 hrs/week · 3 months', array['Bengali', 'Teaching']::text[], 'Recording and checking short reading exercises for a phone app our teachers use in classrooms without books.', '2026-08-13'::date, 'live' from public.ministries m where m.slug = 'dhaka-riverside'
union all
select m.id, 'Station night watch volunteers', 'volunteers', 'urgent', 4, 'children', false, '1 night/week · 6 months', array['Bengali or Hindi', 'Safeguarding']::text[], 'Meeting the night trains alongside our staff and staying with children who arrive alone until the morning team takes over.', '2026-08-30'::date, 'live' from public.ministries m where m.slug = 'kolkata-sealdah'
union all
select m.id, 'Safeguarding policy review', 'expertise', 'soon', 1, 'children', true, '10 hrs total', array['Child safeguarding', 'Policy writing']::text[], 'Review our child-protection policy against current Indian law and good practice, and help us write the staff training that goes with it.', '2026-07-27'::date, 'live' from public.ministries m where m.slug = 'kolkata-sealdah'
union all
select m.id, 'Online shop set-up', 'expertise', 'soon', 1, 'work', true, '15 hrs · 1 month', array['Shopify or Etsy', 'E-commerce']::text[], 'Our tailoring graduates make bags and quilts that sell well at fairs. Set up a small online shop and show two of them how to run it.', '2026-06-30'::date, 'live' from public.ministries m where m.slug = 'mumbai-dharavi'
union all
select m.id, 'Pricing and costing workshop', 'expertise', 'soon', 1, 'work', true, '2 video sessions', array['Small business', 'Costing']::text[], 'Two video workshops for our workshop leads on pricing a product so it pays the maker a fair wage.', '2026-08-10'::date, 'live' from public.ministries m where m.slug = 'mumbai-dharavi'
union all
select m.id, 'Cyclone shelter retrofit funding', 'funding', 'urgent', 0, 'shelter', false, 'single grant', '{}', 'Storm shutters, a raised water tank and a generator for the community hall that three hundred families shelter in during a cyclone.', '2026-08-29'::date, 'live' from public.ministries m where m.slug = 'chennai-coastal'
union all
select m.id, 'Tamil translation checkers', 'volunteers', 'ongoing', 3, 'translation', true, '3 hrs/week', array['Tamil', 'Careful reading']::text[], 'Reading draft passages against the source and flagging anything unclear or unnatural. Shared documents; work whenever suits you.', '2026-05-30'::date, 'live' from public.ministries m where m.slug = 'chennai-coastal'
union all
select m.id, 'Kannada-Hindi phone interpreters', 'volunteers', 'soon', 3, 'refugees', true, '2 hrs/week', array['Kannada', 'Hindi']::text[], 'Helping families talk to schools, clinics and site managers by phone when no one on the call shares a language.', '2026-08-15'::date, 'live' from public.ministries m where m.slug = 'bengaluru-migrant'
union all
select m.id, 'Payroll and compliance advisor', 'expertise', 'ongoing', 1, 'work', true, '3 hrs/month', array['Labour law', 'Payroll']::text[], 'Checking wage slips families bring us against the law, and advising our team on which disputes are worth taking further.', '2026-06-08'::date, 'live' from public.ministries m where m.slug = 'bengaluru-migrant'
union all
select m.id, 'Landslide risk surveyor', 'expertise', 'soon', 1, 'shelter', false, '2 weeks on site', array['Geotechnical survey']::text[], 'Walking the slopes above our rebuild sites and telling us where it is safe to build before the next monsoon.', '2026-08-08'::date, 'live' from public.ministries m where m.slug = 'kathmandu-hillside'
union all
select m.id, 'Online English tutors', 'volunteers', 'ongoing', 4, 'children', true, '1 hr/week', array['English teaching']::text[], 'One-to-one video lessons for teenagers in our youth programme preparing for their school-leaving exams.', '2026-08-17'::date, 'live' from public.ministries m where m.slug = 'kathmandu-hillside'
union all
select m.id, 'Drainage advocacy research', 'expertise', 'soon', 1, 'water', true, '10 hrs total', array['Policy research', 'Urban planning']::text[], 'Pull together the evidence (rainfall, flood reports, city budgets) for a short briefing we will take to the barangay council.', '2026-06-02'::date, 'live' from public.ministries m where m.slug = 'manila-estero'
union all
select m.id, 'Feeding programme cooks', 'volunteers', 'urgent', 3, 'food', false, '2 mornings/week', array['Filipino']::text[], 'Cooking breakfast for around ninety children before school, in our kitchen by the creek.', '2026-09-03'::date, 'live' from public.ministries m where m.slug = 'manila-estero'
union all
select m.id, 'Fire-safety explainer video', 'expertise', 'soon', 1, 'shelter', true, '15 hrs total', array['Animation', 'Indonesian helpful']::text[], 'A two-minute animated video on cooking-fire safety that we can play from a phone at community meetings. The script is drafted; we need it made.', '2026-08-01'::date, 'live' from public.ministries m where m.slug = 'jakarta-kampung'
union all
select m.id, 'Literacy class volunteers', 'volunteers', 'ongoing', 4, 'education', false, '3 hrs/week', array['Indonesian']::text[], 'Helping in after-school reading classes for children aged seven to twelve.', '2026-07-08'::date, 'live' from public.ministries m where m.slug = 'jakarta-kampung'
union all
select m.id, 'Aftercare case consultation', 'expertise', 'urgent', 1, 'prison', true, '2 hrs/fortnight · 6 months', array['Social work', 'Thai helpful']::text[], 'A qualified social worker to review cases with our two aftercare staff by video, and help them plan each person''s first month out.', '2026-08-23'::date, 'live' from public.ministries m where m.slug = 'bangkok-klongtoey'
union all
select m.id, 'Study booklet layout', 'expertise', 'soon', 1, 'discipleship', true, '12 hrs total', array['Layout design', 'InDesign or Affinity']::text[], 'Lay out a twelve-week Thai study booklet for print. The text and translation are done; it needs to be designed.', '2026-07-20'::date, 'live' from public.ministries m where m.slug = 'bangkok-klongtoey'
union all
select m.id, 'English conversation hosts (video)', 'volunteers', 'soon', 4, 'education', true, '1 evening/week · 3 months', array['English', 'Khmer helpful']::text[], 'Hosting a small online conversation group for our evening-class students who want to practise with a native speaker.', '2026-08-20'::date, 'live' from public.ministries m where m.slug = 'phnompenh-riverside'
union all
select m.id, 'Micro-loan partner', 'partners', 'ongoing', 0, 'work', false, 'standing', array['Microfinance']::text[], 'A licensed lender willing to run small loans through our savings groups, with us doing the relationships and the follow-up.', '2026-05-16'::date, 'live' from public.ministries m where m.slug = 'phnompenh-riverside'
union all
select m.id, 'Stilt-school carpenters', 'volunteers', 'urgent', 4, 'education', false, '3 weeks on site', array['Carpentry']::text[], 'Working alongside the community''s own carpenters on the rebuild of the school platform. Lodging with families.', '2026-08-26'::date, 'live' from public.ministries m where m.slug = 'lagos-makoko'
union all
select m.id, 'School logo and signage', 'expertise', 'soon', 1, 'education', true, '8 hrs total', array['Logo design', 'Branding']::text[], 'The rebuilt school needs a name board, a logo and a simple look we can paint on the walls and print on uniforms.', '2026-08-03'::date, 'live' from public.ministries m where m.slug = 'lagos-makoko'
union all
select m.id, 'Wolof translation reviewers', 'volunteers', 'ongoing', 3, 'translation', true, '4 hrs/week', array['Wolof', 'French']::text[], 'Checking draft Wolof passages against the French for accuracy and natural flow. Fully online.', '2026-06-11'::date, 'live' from public.ministries m where m.slug = 'dakar-medina'
union all
select m.id, 'Girls'' football coaches', 'volunteers', 'soon', 2, 'children', false, '2 evenings/week', array['Coaching', 'French or Wolof']::text[], 'Coaching two teams in our girls'' league, in the courtyard on Tuesday and Thursday evenings.', '2026-08-22'::date, 'live' from public.ministries m where m.slug = 'dakar-medina'
union all
select m.id, 'Borehole drilling partner', 'partners', 'urgent', 0, 'water', false, '3 boreholes', array['Drilling']::text[], 'A drilling organisation to sink three boreholes on the western edge of the city, where the piped supply stops.', '2026-09-04'::date, 'live' from public.ministries m where m.slug = 'kinshasa-ngaliema'
union all
select m.id, 'Nurse training course materials', 'expertise', 'soon', 1, 'health', true, '4 hrs/week · 2 months', array['Nurse education', 'French']::text[], 'Help our trainers turn their teaching notes into French-language modules and short quizzes for the training room.', '2026-08-12'::date, 'live' from public.ministries m where m.slug = 'kinshasa-ngaliema'
union all
select m.id, 'Financial literacy course', 'expertise', 'soon', 1, 'work', true, '10 hrs total', array['Financial literacy', 'Amharic helpful']::text[], 'Adapt a simple savings and budgeting course for street traders who keep their accounts in their heads: pictures rather than paragraphs.', '2026-08-18'::date, 'live' from public.ministries m where m.slug = 'addis-merkato'
union all
select m.id, 'Audio editor for Amharic recordings', 'expertise', 'ongoing', 1, 'translation', true, '4 hrs/week', array['Audio editing', 'Amharic helpful']::text[], 'Editing and mastering the Scripture readings our volunteers record in the Merkato room, for people who do not read.', '2026-05-28'::date, 'live' from public.ministries m where m.slug = 'addis-merkato'
union all
select m.id, 'Gang-exit mentors', 'volunteers', 'urgent', 3, 'prison', false, '1 day/week · 1 year', array['Xhosa', 'Mentoring']::text[], 'Walking alongside young men leaving gangs, with our staff, for a full year.', '2026-08-31'::date, 'live' from public.ministries m where m.slug = 'capetown-khayelitsha'
union all
select m.id, 'Trauma debrief facilitator', 'expertise', 'soon', 1, 'trauma', true, '3 hrs/fortnight', array['Trauma debriefing']::text[], 'Leading a video debrief for our mentors after hard weeks, so the people doing this work have somewhere to put it.', '2026-08-07'::date, 'live' from public.ministries m where m.slug = 'capetown-khayelitsha'
union all
select m.id, 'Project management support', 'expertise', 'urgent', 1, 'shelter', true, '4 hrs/week · 3 months', array['Project management', 'Arabic or French helpful']::text[], 'Help our site lead plan the last ninety households: a schedule, a materials tracker, and a weekly call to keep it on track.', '2026-08-25'::date, 'live' from public.ministries m where m.slug = 'beirut-karantina'
union all
select m.id, 'Window glazing supplies', 'supplies', 'soon', 0, 'shelter', false, '90 windows', '{}', 'Glass, frames and sealant for the last ninety windows in the quarter closest to the port.', '2026-07-24'::date, 'live' from public.ministries m where m.slug = 'beirut-karantina'
union all
select m.id, 'Social media volunteer', 'volunteers', 'soon', 1, 'children', true, '3 hrs/week', array['Social media', 'Russian helpful']::text[], 'Running our Instagram and Facebook: two posts a week from the photos and stories our youth leaders send.', '2026-08-14'::date, 'live' from public.ministries m where m.slug = 'bishkek-novostroyka'
union all
select m.id, 'Winter coal fund', 'funding', 'soon', 0, 'shelter', false, 'seasonal', '{}', 'Coal for sixty households before the first hard frost, bought in bulk in October while it is cheapest.', '2026-08-02'::date, 'live' from public.ministries m where m.slug = 'bishkek-novostroyka'
union all
select m.id, 'Newcomer welcome hosts', 'volunteers', 'ongoing', 6, 'refugees', false, '1 evening/week', array['English', 'Cooking']::text[], 'Cooking and sharing the weekly Scarborough meal with newly arrived claimants.', '2026-07-16'::date, 'live' from public.ministries m where m.slug = 'toronto-newcomer'
union all
select m.id, 'Immigration lawyer (pro bono)', 'expertise', 'soon', 1, 'refugees', true, '4 hrs/month', array['Immigration law']::text[], 'Reviewing claims by video before hearings, and joining the monthly table when you can.', '2026-08-11'::date, 'live' from public.ministries m where m.slug = 'toronto-newcomer'
;

commit;

-- What you should see:
--   select count(*) from public.ministries;                     -- 32
--   select count(*) from public.needs where status = 'live';    -- 65
