-- Terra — demo seed. Generated by tools/build_seed.mjs; do not edit by hand.
--
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query →
-- paste → Run), the same way the schema migration was applied. The editor
-- runs as a privileged role, which is what makes it able to write `needs`:
-- that table deliberately has no insert policy, so neither the anon key nor
-- a signed-in user can add rows. Only the service role and the SQL editor.
--
-- Safe to re-run. Everything below is owned by one fixed demo user, and the
-- script clears that user's rows before inserting, so you get the same 32
-- ministries and 65 needs every time rather than a second copy of them.
--
-- ALL OF THIS DATA IS FICTIONAL. Every organisation, person and need is
-- invented, and every contact address is on example.org, which cannot
-- receive mail. To remove it again:
--
--   delete from auth.users where id = '00000000-0000-4000-8000-00000000d3m0';
--
-- which cascades to the profile, the ministries and their needs.

begin;

-- ---------------------------------------------------------- demo owner
--
-- ministries.owner_id is not null and references profiles(id), which
-- references auth.users(id) — so the seed needs a user to hang off. It has
-- no password at all: the column is nullable (OAuth users carry none), and a
-- null there means no credential can ever match, which is what you want of
-- an account that exists only to own rows. Writing a hash instead would have
-- pulled in pgcrypto's crypt() for no benefit. The on_auth_user_created
-- trigger writes the matching profile.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  created_at, updated_at, raw_app_meta_data, raw_user_meta_data,
  confirmation_token, recovery_token, email_change_token_new, email_change
)
values (
  '00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-00000000d3m0', 'authenticated', 'authenticated',
  'demo@example.org', null, now(),
  now(), now(), '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Terra demo data","role":"ministry"}'::jsonb,
  '', '', '', ''
)
on conflict (id) do nothing;

-- The trigger covers a fresh insert; this covers a database where the user
-- already exists but the profile was removed.
insert into public.profiles (id, full_name, role)
values ('00000000-0000-4000-8000-00000000d3m0', 'Terra demo data', 'ministry')
on conflict (id) do update set role = 'ministry';

-- Clear this owner's previous seed. Needs cascade from ministries.
delete from public.ministries where owner_id = '00000000-0000-4000-8000-00000000d3m0';

-- ---------------------------------------------------------- ministries
insert into public.ministries
  (owner_id, slug, name, city, country, lat, lon, region, focus, since, staff, languages, contact, blurb)
values
  ('00000000-0000-4000-8000-00000000d3m0', 'ulaanbaatar-ger', 'Ulaanbaatar Ger Districts Trust', 'Ulaanbaatar', 'Mongolia', 47.9186, 106.9177, 'asia', array['shelter', 'children']::text[], 2011, 9, array['Mongolian', 'Russian']::text[], 'hello@ulaanbaatar-ger.example.org', 'Works through the winter in the unserviced ger districts on the city''s northern slopes, where families heat single-room tents with raw coal.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'aleppo-neighbours', 'Aleppo Neighbours Initiative', 'Aleppo', 'Syria', 36.2021, 37.1343, 'mena', array['shelter', 'trauma']::text[], 2017, 14, array['Arabic', 'English']::text[], 'salaam@aleppo-neighbours.example.org', 'Neighbourhood committees clearing and re-roofing damaged buildings street by street, starting with the households that never left.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'cairo-garbage-city', 'Cairo Garbage City Hope', 'Cairo', 'Egypt', 30.0444, 31.2357, 'mena', array['health', 'work']::text[], 2006, 22, array['Arabic', 'English']::text[], 'office@cairo-hope.example.org', 'Walks with the Zabbaleen recycling families of Manshiyat Naser: clinic days, school fees, and safer ways to do the sorting work.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'nairobi-mathare', 'Mathare Hope Collective', 'Nairobi', 'Kenya', -1.2864, 36.8172, 'africa', array['children', 'health', 'translation']::text[], 2009, 18, array['Swahili', 'English', 'Kikuyu']::text[], 'karibu@mathare-hope.example.org', 'A church-run centre in the Mathare valley: after-school classes, a two-room clinic, and a Swahili study group that writes its own material.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'karachi-dockside', 'Karachi Dockside Mission', 'Karachi', 'Pakistan', 24.8607, 67.0011, 'asia', array['work', 'education']::text[], 2014, 11, array['Urdu', 'Sindhi', 'English']::text[], 'contact@karachi-dockside.example.org', 'Among the fishing families of Ibrahim Hyderi — boat safety, school enrolment, and literacy classes held between tides.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'amman-welcome', 'Amman Refugee Welcome', 'Amman', 'Jordan', 31.9454, 35.9284, 'mena', array['refugees', 'trauma']::text[], 2013, 26, array['Arabic', 'English']::text[], 'welcome@amman-welcome.example.org', 'First-week accompaniment for newly arrived families: paperwork, a mattress, and someone who speaks both languages in the room.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kyiv-winter', 'Kyiv Winter Response', 'Kyiv', 'Ukraine', 50.4501, 30.5234, 'europe', array['shelter', 'food']::text[], 2022, 31, array['Ukrainian', 'Russian', 'English']::text[], 'shtab@kyiv-winter.example.org', 'Keeps heat and light in apartment blocks through the cold months: generators, boiler repairs, and a hot meal round at street level.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'warsaw-hosts', 'Warsaw Border Hosts', 'Warsaw', 'Poland', 52.2297, 21.0122, 'europe', array['refugees']::text[], 2022, 8, array['Polish', 'Ukrainian', 'English']::text[], 'dom@warsaw-hosts.example.org', 'Matches arriving families with host households, then stays alongside both for the first hundred days.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'london-estates', 'London Estates Fellowship', 'London', 'United Kingdom', 51.5072, -0.1276, 'europe', array['children', 'food']::text[], 1998, 12, array['English', 'Bengali', 'Somali']::text[], 'hello@london-estates.example.org', 'Youth clubs and a food round on three east London estates, run by people who grew up on them.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'madrid-puente', 'Madrid Puente Comunidad', 'Madrid', 'Spain', 40.4168, -3.7038, 'europe', array['education', 'work']::text[], 2015, 7, array['Spanish', 'Arabic', 'English']::text[], 'hola@madrid-puente.example.org', 'Spanish classes and first-job coaching in Usera, for people who arrived with qualifications nobody here will read.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'lima-pueblos', 'Lima Pueblos Jóvenes', 'Lima', 'Peru', -12.0464, -77.0428, 'latam', array['water', 'children']::text[], 2008, 15, array['Spanish', 'Quechua']::text[], 'hola@lima-pueblos.example.org', 'On the sand hills above the city, where water arrives by truck: tanks, taps, and a children''s programme that runs all summer.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bogota-casa', 'Bogotá Casa Abierta', 'Bogotá', 'Colombia', 4.711, -74.0721, 'latam', array['refugees', 'trauma']::text[], 2018, 19, array['Spanish', 'English']::text[], 'casa@bogota-abierta.example.org', 'A day house for Venezuelan families still on the move: casework, a play room, and somewhere to leave a bag.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'saopaulo-luz', 'São Paulo Favela Luz', 'São Paulo', 'Brazil', -23.5505, -46.6333, 'latam', array['children', 'discipleship']::text[], 2004, 21, array['Portuguese']::text[], 'oi@favela-luz.example.org', 'A music school and small-group network in Brasilândia, with instruments that go home with the students.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'santiago-manos', 'Santiago Manos Abiertas', 'Santiago', 'Chile', -33.4489, -70.6693, 'latam', array['food', 'shelter']::text[], 2012, 6, array['Spanish', 'Haitian Creole']::text[], 'manos@santiago-abiertas.example.org', 'Night rounds through the centre in winter: soup, blankets, and the slow work of getting someone indoors.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'dhaka-riverside', 'Dhaka Riverside Trust', 'Dhaka', 'Bangladesh', 23.8103, 90.4125, 'asia', array['shelter', 'education']::text[], 2010, 24, array['Bengali', 'English']::text[], 'trust@dhaka-riverside.example.org', 'Builds and rebuilds along the Buriganga for families who move every flood season, and teaches their children to read.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kolkata-sealdah', 'Kolkata Sealdah Care', 'Kolkata', 'India', 22.5726, 88.3639, 'asia', array['children', 'health']::text[], 1996, 29, array['Bengali', 'Hindi', 'English']::text[], 'care@sealdah.example.org', 'Meets children arriving alone on the night trains into Sealdah station, and keeps meeting them until there is somewhere to go.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'mumbai-dharavi', 'Mumbai Dharavi Neighbours', 'Mumbai', 'India', 19.076, 72.8777, 'asia', array['work']::text[], 2007, 13, array['Marathi', 'Hindi', 'English']::text[], 'hello@dharavi-neighbours.example.org', 'Tailoring and leatherwork training inside Dharavi, run with the workshops rather than around them.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'chennai-coastal', 'Chennai Coastal Hope', 'Chennai', 'India', 13.0827, 80.2707, 'asia', array['shelter', 'translation']::text[], 2005, 16, array['Tamil', 'English']::text[], 'hope@chennai-coastal.example.org', 'Cyclone-season preparation in the fishing settlements north of the harbour, plus a Tamil translation desk.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bengaluru-migrant', 'Bengaluru Migrant Welcome', 'Bengaluru', 'India', 12.9716, 77.5946, 'asia', array['refugees', 'work']::text[], 2016, 10, array['Kannada', 'Hindi', 'English']::text[], 'namaskara@blr-welcome.example.org', 'For construction-site families who arrive from three states away: wage disputes, school places, and a language bridge.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kathmandu-hillside', 'Kathmandu Hillside Trust', 'Kathmandu', 'Nepal', 27.7172, 85.324, 'asia', array['shelter', 'children']::text[], 2015, 12, array['Nepali', 'English']::text[], 'namaste@kathmandu-hillside.example.org', 'Rebuilds on unstable ground above the valley, and runs a youth programme for the families waiting on it.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'manila-estero', 'Manila Estero Fellowship', 'Manila', 'Philippines', 14.5995, 120.9842, 'asia', array['water', 'food']::text[], 2003, 17, array['Filipino', 'English']::text[], 'kumusta@manila-estero.example.org', 'Along the esteros of Tondo: creek clean-ups, a feeding programme, and a fight for drainage that actually drains.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'jakarta-kampung', 'Jakarta Kampung Bright', 'Jakarta', 'Indonesia', -6.2088, 106.8456, 'asia', array['shelter', 'education']::text[], 2013, 14, array['Indonesian', 'Javanese']::text[], 'salam@kampung-bright.example.org', 'Fire safety and literacy in the dense kampungs of North Jakarta, where one cooking fire takes forty homes.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bangkok-klongtoey', 'Bangkok Klong Toey Friends', 'Bangkok', 'Thailand', 13.7563, 100.5018, 'asia', array['prison', 'discipleship']::text[], 2001, 9, array['Thai', 'English']::text[], 'sawasdee@klongtoey-friends.example.org', 'Prison visiting and aftercare around the port district: the first month out is the one that decides the rest.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'phnompenh-riverside', 'Phnom Penh Riverside Care', 'Phnom Penh', 'Cambodia', 11.5564, 104.9282, 'asia', array['education', 'work']::text[], 2011, 11, array['Khmer', 'English']::text[], 'suosdey@pp-riverside.example.org', 'Evening classes and small loans for families along the riverfront, most of them one eviction from starting again.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'lagos-makoko', 'Lagos Makoko Waterline', 'Lagos', 'Nigeria', 6.5244, 3.3792, 'africa', array['education', 'shelter']::text[], 2012, 13, array['Yoruba', 'English', 'Egun']::text[], 'hello@makoko-waterline.example.org', 'A school on stilts over the lagoon, rebuilt by the community''s own carpenters roughly every four years.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'dakar-medina', 'Dakar Médina Espoir', 'Dakar', 'Senegal', 14.7167, -17.4677, 'africa', array['translation', 'children']::text[], 2010, 8, array['Wolof', 'French']::text[], 'bonjour@medina-espoir.example.org', 'A Wolof translation circle and a girls'' football league, both of which fill the same courtyard on different evenings.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'kinshasa-ngaliema', 'Kinshasa Ngaliema Mission', 'Kinshasa', 'DR Congo', -4.4419, 15.2663, 'africa', array['water', 'health']::text[], 1999, 20, array['French', 'Lingala']::text[], 'bonjour@ngaliema-mission.example.org', 'Boreholes and a nurse-training room on the western edge of the city, where the piped supply stops.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'addis-merkato', 'Addis Merkato Care', 'Addis Ababa', 'Ethiopia', 9.032, 38.7469, 'africa', array['work', 'translation']::text[], 2008, 15, array['Amharic', 'Oromo', 'English']::text[], 'selam@merkato-care.example.org', 'Savings groups among Merkato''s street traders, and an Amharic audio recording room for people who do not read.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'capetown-khayelitsha', 'Khayelitsha Light', 'Cape Town', 'South Africa', -33.9249, 18.4241, 'africa', array['prison', 'trauma']::text[], 2006, 17, array['Xhosa', 'Afrikaans', 'English']::text[], 'molo@khayelitsha-light.example.org', 'Gang-exit mentoring and trauma debriefs, run by people the young men will actually listen to.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'beirut-karantina', 'Beirut Karantina Rebuild', 'Beirut', 'Lebanon', 33.8938, 35.5018, 'mena', array['shelter']::text[], 2020, 10, array['Arabic', 'French', 'English']::text[], 'ahla@karantina-rebuild.example.org', 'Still finishing the windows and roofs the port blast took out, household by household, in the quarter closest to it.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'bishkek-novostroyka', 'Bishkek Novostroyka Trust', 'Bishkek', 'Kyrgyzstan', 42.8746, 74.5698, 'asia', array['children', 'shelter']::text[], 2014, 7, array['Kyrgyz', 'Russian']::text[], 'salam@bishkek-trust.example.org', 'In the unplanned novostroyka settlements at the city edge: a youth room, and coal before the first hard frost.'),
  ('00000000-0000-4000-8000-00000000d3m0', 'toronto-newcomer', 'Toronto Newcomer Table', 'Toronto', 'Canada', 43.6532, -79.3832, 'northam', array['refugees']::text[], 2017, 6, array['English', 'French', 'Tigrinya', 'Dari']::text[], 'welcome@newcomer-table.example.org', 'A weekly table in Scarborough where claimants, hosts and a volunteer lawyer end up at the same meal.')
on conflict (slug) do update set
  owner_id = excluded.owner_id, name = excluded.name, city = excluded.city,
  country = excluded.country, lat = excluded.lat, lon = excluded.lon,
  region = excluded.region, focus = excluded.focus, since = excluded.since,
  staff = excluded.staff, languages = excluded.languages,
  contact = excluded.contact, blurb = excluded.blurb;

-- --------------------------------------------------------------- needs
--
-- status 'live' explicitly: the column defaults to pending_review so that
-- anything reaching the table without passing moderation stays invisible,
-- and only live rows are readable by the public policy. Seed data has no
-- moderation pass to go through, so it is marked live here.
--
-- Joined on slug rather than carrying ministry uuids, so the ids stay
-- whatever Postgres generated and this file has no machine state in it.
insert into public.needs
  (ministry_id, title, type, urgency, people, focus, remote, commitment, skills, detail, posted, status)
select m.id, 'Ger insulation kits', 'supplies', 'urgent', 0, 'shelter', false, '40 kits before November', array['Logistics']::text[], 'Felt and canvas outer layers for forty gers on the northern slopes. Nights are already below freezing and the coal ration does not stretch to an uninsulated tent.', '2026-08-29'::date, 'live' from public.ministries m where m.slug = 'ulaanbaatar-ger'
union all
select m.id, 'Winter night shelter volunteers', 'volunteers', 'urgent', 14, 'shelter', false, '2 nights/week · 4 months', array['Mongolian', 'First aid']::text[], 'Two people per night from December through March, on a rota with staff. Training and a bed in the building are provided.', '2026-08-21'::date, 'live' from public.ministries m where m.slug = 'ulaanbaatar-ger'
union all
select m.id, 'Structural engineer (remote review)', 'expertise', 'urgent', 2, 'shelter', true, '6 hrs/week · 3 months', array['Structural engineering', 'Arabic helpful']::text[], 'Reviewing photographs, measurements and sketches of damaged load-bearing walls, and telling the committee which buildings can be reoccupied and which cannot. Fully remote, on our timetable.', '2026-09-01'::date, 'live' from public.ministries m where m.slug = 'aleppo-neighbours'
union all
select m.id, 'Rubble clearance crew', 'volunteers', 'soon', 24, 'shelter', false, '2 weeks on site', array['Manual labour']::text[], 'Two-week rotations clearing four streets by hand and barrow. Accommodation with local families.', '2026-08-11'::date, 'live' from public.ministries m where m.slug = 'aleppo-neighbours'
union all
select m.id, 'Occupational health advisor', 'expertise', 'urgent', 1, 'health', true, '4 hrs/week · 6 months', array['Occupational health', 'Arabic helpful']::text[], 'Help us write sorting-line safety guidance the families will actually use, and train four of our staff to teach it.', '2026-08-30'::date, 'live' from public.ministries m where m.slug = 'cairo-garbage-city'
union all
select m.id, 'Recycling co-op start-up funding', 'funding', 'soon', 0, 'work', false, 'single grant', '{}', 'Seed capital for a family-run sorting co-operative: a baler, gloves and masks for twelve, and three months of working capital.', '2026-07-30'::date, 'live' from public.ministries m where m.slug = 'cairo-garbage-city'
union all
select m.id, 'Swahili Bible study reviewers', 'volunteers', 'soon', 6, 'translation', true, '4 hrs/week · 3 months', array['Swahili', 'Theology']::text[], 'We write our own study material and need first-language Swahili readers with some theological training to check it before it goes to print.', '2026-08-18'::date, 'live' from public.ministries m where m.slug = 'nairobi-mathare'
union all
select m.id, 'Clinic nurse (6 months)', 'volunteers', 'urgent', 2, 'health', false, 'full time · 6 months', array['Nursing', 'Registration']::text[], 'Two registered nurses to hold the clinic''s morning list while our own two staff complete their midwifery training.', '2026-08-26'::date, 'live' from public.ministries m where m.slug = 'nairobi-mathare'
union all
select m.id, 'Solar study lamps', 'supplies', 'soon', 0, 'education', false, '120 lamps', '{}', 'The after-school classes finish after dark and most homes have no reliable light. Rechargeable lamps go home with the students.', '2026-08-04'::date, 'live' from public.ministries m where m.slug = 'nairobi-mathare'
union all
select m.id, 'Boat-safety trainers', 'expertise', 'soon', 3, 'work', false, '3 weeks', array['Maritime safety', 'Urdu']::text[], 'Train forty crew in cold-water survival, flares and radio use before the winter fishing season.', '2026-08-14'::date, 'live' from public.ministries m where m.slug = 'karachi-dockside'
union all
select m.id, 'School exercise books', 'supplies', 'ongoing', 0, 'education', false, 'termly', '{}', 'Standing need: exercise books and pencils for around two hundred children each term.', '2026-06-19'::date, 'live' from public.ministries m where m.slug = 'karachi-dockside'
union all
select m.id, 'Arabic-English interpreters', 'volunteers', 'urgent', 11, 'refugees', false, '1 day/week · 6 months', array['Arabic', 'English']::text[], 'Sitting with families through registration and medical appointments. This is the single thing we are most short of.', '2026-08-31'::date, 'live' from public.ministries m where m.slug = 'amman-welcome'
union all
select m.id, 'Trauma counselling supervision', 'expertise', 'soon', 2, 'trauma', true, '2 hrs/fortnight · 12 months', array['Clinical supervision', 'Trauma']::text[], 'Clinical supervision for six caseworkers carrying heavy stories with no one above them to take it to.', '2026-08-09'::date, 'live' from public.ministries m where m.slug = 'amman-welcome'
union all
select m.id, 'Generators and fuel', 'supplies', 'urgent', 0, 'shelter', false, 'before first frost', '{}', 'Six 5 kW generators and a fuel line for the winter, covering four apartment blocks and a stairwell clinic.', '2026-09-02'::date, 'live' from public.ministries m where m.slug = 'kyiv-winter'
union all
select m.id, 'Boiler technicians', 'expertise', 'urgent', 4, 'shelter', false, '3 weeks', array['Heating systems', 'Welding']::text[], 'Repairs to block heating plant before the season. Our own crew can do the pipework but not the burners.', '2026-08-25'::date, 'live' from public.ministries m where m.slug = 'kyiv-winter'
union all
select m.id, 'Host family coordinators', 'volunteers', 'soon', 5, 'refugees', false, '6 hrs/week · 6 months', array['Polish', 'Ukrainian']::text[], 'Each coordinator holds eight or nine matches: the weekly call, the awkward conversation, the paperwork.', '2026-08-07'::date, 'live' from public.ministries m where m.slug = 'warsaw-hosts'
union all
select m.id, 'Legal aid partner', 'partners', 'ongoing', 0, 'refugees', false, 'standing referral', array['Immigration law']::text[], 'A firm or clinic willing to take referred residency cases at a rate our families can meet.', '2026-05-22'::date, 'live' from public.ministries m where m.slug = 'warsaw-hosts'
union all
select m.id, 'Youth club mentors', 'volunteers', 'soon', 14, 'children', false, '1 evening/week · 1 year', array['Youth work', 'DBS check']::text[], 'Thursday and Friday clubs for eleven to sixteens. We would rather have fourteen people for a year than forty for a term.', '2026-08-16'::date, 'live' from public.ministries m where m.slug = 'london-estates'
union all
select m.id, 'Food bank drivers', 'volunteers', 'ongoing', 4, 'food', false, '1 morning/week', array['Driving licence']::text[], 'Collections from three supermarkets and a wholesaler, then the round. Van provided.', '2026-07-11'::date, 'live' from public.ministries m where m.slug = 'london-estates'
union all
select m.id, 'Spanish literacy tutors', 'volunteers', 'soon', 7, 'education', false, '3 hrs/week · 4 months', array['Spanish', 'Teaching']::text[], 'Small-group classes for adults, most of them working nights. Sessions are late afternoon.', '2026-08-12'::date, 'live' from public.ministries m where m.slug = 'madrid-puente'
union all
select m.id, 'Employment coach', 'expertise', 'ongoing', 1, 'work', false, '2 days/week', array['Recruitment', 'Spanish']::text[], 'Someone who knows how Spanish employers read a foreign CV, and can sit with people while they rewrite theirs.', '2026-06-28'::date, 'live' from public.ministries m where m.slug = 'madrid-puente'
union all
select m.id, 'Water tank installation', 'supplies', 'urgent', 0, 'water', false, '18 tanks', '{}', '1,100-litre tanks and stands for eighteen households at the top of the hill, where the truck cannot reach.', '2026-08-28'::date, 'live' from public.ministries m where m.slug = 'lima-pueblos'
union all
select m.id, 'Children''s programme leaders', 'volunteers', 'soon', 12, 'children', false, '6 weeks, summer', array['Spanish', 'Youth work']::text[], 'Our January to February programme runs for six weeks and reaches around three hundred children.', '2026-08-02'::date, 'live' from public.ministries m where m.slug = 'lima-pueblos'
union all
select m.id, 'Venezuelan family caseworkers', 'volunteers', 'urgent', 6, 'refugees', false, '4 days/week · 6 months', array['Spanish', 'Casework']::text[], 'Caseload of around twenty families each, most of them in the city for less than a month.', '2026-08-27'::date, 'live' from public.ministries m where m.slug = 'bogota-casa'
union all
select m.id, 'Trauma-informed play therapist', 'expertise', 'soon', 2, 'trauma', false, '2 days/week · 6 months', array['Play therapy', 'Spanish']::text[], 'The play room is the only place some of these children have been still since they left. We need people who know what to do with that.', '2026-08-06'::date, 'live' from public.ministries m where m.slug = 'bogota-casa'
union all
select m.id, 'Music school instruments', 'supplies', 'ongoing', 0, 'children', false, 'rolling', '{}', 'Violins, flutes and guitars in playable condition. Instruments go home with students, which is the point and also why they wear out.', '2026-07-03'::date, 'live' from public.ministries m where m.slug = 'saopaulo-luz'
union all
select m.id, 'Portuguese discipleship leaders', 'volunteers', 'soon', 11, 'discipleship', false, '1 evening/week · 1 year', array['Portuguese']::text[], 'Small groups of eight to ten, meeting in homes across Brasilândia.', '2026-08-19'::date, 'live' from public.ministries m where m.slug = 'saopaulo-luz'
union all
select m.id, 'Night outreach team', 'volunteers', 'ongoing', 6, 'food', false, '1 night/week · winter', array['Spanish']::text[], 'Two vehicles, four stops, three hours. Soup, blankets, and the conversation that eventually gets someone indoors.', '2026-06-14'::date, 'live' from public.ministries m where m.slug = 'santiago-manos'
union all
select m.id, 'Winter blankets', 'supplies', 'soon', 0, 'shelter', false, '400 blankets', '{}', 'New or good-condition blankets before June. We give away roughly four hundred a winter and do not get them back.', '2026-08-05'::date, 'live' from public.ministries m where m.slug = 'santiago-manos'
union all
select m.id, 'Flood-resilient housing designer', 'expertise', 'urgent', 2, 'shelter', true, '8 hrs/week · 4 months', array['Architecture', 'Flood engineering']::text[], 'A raised single-room design that can be built by the families themselves from materials sold within two kilometres of the river.', '2026-08-24'::date, 'live' from public.ministries m where m.slug = 'dhaka-riverside'
union all
select m.id, 'Bengali literacy tutors', 'volunteers', 'soon', 16, 'education', false, '4 hrs/week · 6 months', array['Bengali', 'Teaching']::text[], 'Morning classes for children who work in the afternoons, and an evening class for their mothers.', '2026-08-13'::date, 'live' from public.ministries m where m.slug = 'dhaka-riverside'
union all
select m.id, 'Station night watch volunteers', 'volunteers', 'urgent', 14, 'children', false, '1 night/week · 6 months', array['Bengali or Hindi', 'Safeguarding']::text[], 'Pairs on the platforms between 10pm and 4am, when children arriving alone are at the most risk. Training is four evenings.', '2026-08-30'::date, 'live' from public.ministries m where m.slug = 'kolkata-sealdah'
union all
select m.id, 'Paediatric nurse', 'volunteers', 'soon', 2, 'health', false, 'full time · 12 months', array['Paediatric nursing']::text[], 'Our shelter holds up to sixty children and currently borrows a nurse two mornings a week.', '2026-07-27'::date, 'live' from public.ministries m where m.slug = 'kolkata-sealdah'
union all
select m.id, 'Sewing machines and thread', 'supplies', 'ongoing', 0, 'work', false, 'rolling', '{}', 'Industrial machines for the training room. Graduates take a reconditioned machine with them, so the room empties itself.', '2026-06-30'::date, 'live' from public.ministries m where m.slug = 'mumbai-dharavi'
union all
select m.id, 'Vocational trainers', 'volunteers', 'soon', 5, 'work', false, '2 days/week · 6 months', array['Tailoring or leatherwork', 'Hindi']::text[], 'Trade skills taught by people who have done the trade. Teaching experience is welcome but not the main thing.', '2026-08-10'::date, 'live' from public.ministries m where m.slug = 'mumbai-dharavi'
union all
select m.id, 'Cyclone shelter retrofit funding', 'funding', 'urgent', 0, 'shelter', false, 'single grant', '{}', 'Roof anchors, shutters and a water tank for two community shelters, before the north-east monsoon in October.', '2026-08-29'::date, 'live' from public.ministries m where m.slug = 'chennai-coastal'
union all
select m.id, 'Tamil translation checkers', 'volunteers', 'ongoing', 4, 'translation', true, '3 hrs/week', array['Tamil', 'Careful reading']::text[], 'First-language Tamil readers to check drafts against the source. Fully remote, and we send you the passages a fortnight ahead.', '2026-05-30'::date, 'live' from public.ministries m where m.slug = 'chennai-coastal'
union all
select m.id, 'Kannada-Hindi interpreters', 'volunteers', 'soon', 6, 'refugees', false, '1 day/week · 6 months', array['Kannada', 'Hindi']::text[], 'Site visits and wage-dispute meetings, where the family and the contractor do not share a language.', '2026-08-15'::date, 'live' from public.ministries m where m.slug = 'bengaluru-migrant'
union all
select m.id, 'Payroll and compliance advisor', 'expertise', 'ongoing', 1, 'work', true, '3 hrs/month', array['Labour law', 'Payroll']::text[], 'We win wage cases we understand and lose the ones we do not. Occasional advice would change that.', '2026-06-08'::date, 'live' from public.ministries m where m.slug = 'bengaluru-migrant'
union all
select m.id, 'Landslide risk surveyor', 'expertise', 'soon', 2, 'shelter', false, '3 weeks', array['Geotechnical survey']::text[], 'Survey of eleven sites above the valley before we commit to rebuilding on any of them.', '2026-08-08'::date, 'live' from public.ministries m where m.slug = 'kathmandu-hillside'
union all
select m.id, 'Nepali youth workers', 'volunteers', 'soon', 10, 'children', false, '2 afternoons/week · 1 year', array['Nepali', 'Youth work']::text[], 'For the families waiting on a rebuild, which in practice means their teenagers have nowhere to be.', '2026-08-17'::date, 'live' from public.ministries m where m.slug = 'kathmandu-hillside'
union all
select m.id, 'Estero clean-up partners', 'partners', 'ongoing', 0, 'water', false, 'standing', array['Waste management']::text[], 'An organisation that can take what we pull out of the creeks. We can clear it; we cannot dispose of it.', '2026-06-02'::date, 'live' from public.ministries m where m.slug = 'manila-estero'
union all
select m.id, 'Feeding programme cooks', 'volunteers', 'urgent', 11, 'food', false, '2 mornings/week', array['Filipino']::text[], 'Four hundred meals a day, five days a week, from two kitchens. We are running it on six people.', '2026-09-03'::date, 'live' from public.ministries m where m.slug = 'manila-estero'
union all
select m.id, 'Fire-safety training', 'expertise', 'soon', 2, 'shelter', false, '2 weeks', array['Fire safety', 'Indonesian']::text[], 'Train forty kampung volunteers in prevention, evacuation routes and first response. One cooking fire takes forty homes here.', '2026-08-01'::date, 'live' from public.ministries m where m.slug = 'jakarta-kampung'
union all
select m.id, 'Indonesian literacy volunteers', 'volunteers', 'ongoing', 13, 'education', false, '3 hrs/week', array['Indonesian']::text[], 'Afternoon reading groups in six kampungs, run out of whatever room is free.', '2026-07-08'::date, 'live' from public.ministries m where m.slug = 'jakarta-kampung'
union all
select m.id, 'Aftercare social worker', 'volunteers', 'urgent', 3, 'prison', false, 'full time · 12 months', array['Social work', 'Thai']::text[], 'The first month after release decides the rest. We can meet people at the gate but not walk with them past week two.', '2026-08-23'::date, 'live' from public.ministries m where m.slug = 'bangkok-klongtoey'
union all
select m.id, 'Thai discipleship material', 'supplies', 'soon', 0, 'discipleship', false, '300 sets', '{}', 'Printed Thai study sets for prison groups, in a format the wardens will allow inside.', '2026-07-20'::date, 'live' from public.ministries m where m.slug = 'bangkok-klongtoey'
union all
select m.id, 'Khmer-English teachers', 'volunteers', 'soon', 6, 'education', false, '4 evenings/week · 6 months', array['English teaching', 'Khmer helpful']::text[], 'Evening English classes, which is the qualification that changes what work is available on the riverfront.', '2026-08-20'::date, 'live' from public.ministries m where m.slug = 'phnompenh-riverside'
union all
select m.id, 'Micro-loan partner', 'partners', 'ongoing', 0, 'work', false, 'standing', array['Microfinance']::text[], 'A lender that will work at our families'' scale without the interest rates that undo the loan.', '2026-05-16'::date, 'live' from public.ministries m where m.slug = 'phnompenh-riverside'
union all
select m.id, 'Stilt-school carpenters', 'volunteers', 'urgent', 10, 'education', false, '5 weeks on site', array['Carpentry']::text[], 'The school platform is due its rebuild. Our own carpenters lead; we need hands and a second boat.', '2026-08-26'::date, 'live' from public.ministries m where m.slug = 'lagos-makoko'
union all
select m.id, 'Solar lighting units', 'supplies', 'soon', 0, 'shelter', false, '80 units', '{}', 'Roof-mounted units for eighty homes over the water, where a kerosene lamp on a timber floor is the alternative.', '2026-08-03'::date, 'live' from public.ministries m where m.slug = 'lagos-makoko'
union all
select m.id, 'Wolof translation reviewers', 'volunteers', 'ongoing', 5, 'translation', true, '4 hrs/week', array['Wolof', 'French']::text[], 'Reading drafts aloud with us over a call, which is how we catch what reads badly in Wolof.', '2026-06-11'::date, 'live' from public.ministries m where m.slug = 'dakar-medina'
union all
select m.id, 'Girls'' football coaches', 'volunteers', 'soon', 4, 'children', false, '2 evenings/week', array['Coaching', 'French or Wolof']::text[], 'Four teams, two evenings, one courtyard. The league has a waiting list we cannot use.', '2026-08-22'::date, 'live' from public.ministries m where m.slug = 'dakar-medina'
union all
select m.id, 'Borehole drilling partner', 'partners', 'urgent', 0, 'water', false, '3 boreholes', array['Drilling']::text[], 'A driller who will work the western edge of the city at cost. We have the sites, the permissions and the community committees.', '2026-09-04'::date, 'live' from public.ministries m where m.slug = 'kinshasa-ngaliema'
union all
select m.id, 'French-speaking nurse trainers', 'expertise', 'soon', 3, 'health', false, '6 weeks', array['Nurse training', 'French']::text[], 'Six-week intensive for fourteen trainee nurses, twice a year. We can host and feed; we cannot teach it.', '2026-08-12'::date, 'live' from public.ministries m where m.slug = 'kinshasa-ngaliema'
union all
select m.id, 'Savings group leads', 'volunteers', 'soon', 6, 'work', false, '1 day/week · 1 year', array['Amharic', 'Bookkeeping']::text[], 'Each lead holds four groups of around twenty traders: the weekly meeting, the ledger, the argument about the ledger.', '2026-08-18'::date, 'live' from public.ministries m where m.slug = 'addis-merkato'
union all
select m.id, 'Amharic audio Bible recording', 'expertise', 'ongoing', 2, 'translation', true, '6 hrs/week', array['Audio engineering', 'Amharic']::text[], 'Editing and mastering recordings made in our own room, for traders who do not read. Remote is fine; we send the takes.', '2026-05-28'::date, 'live' from public.ministries m where m.slug = 'addis-merkato'
union all
select m.id, 'Gang-exit mentors', 'volunteers', 'urgent', 6, 'prison', false, '2 days/week · 2 years', array['Xhosa', 'Mentoring']::text[], 'Two years, because eighteen months is where it usually falls apart. Most of our mentors have walked this themselves.', '2026-08-31'::date, 'live' from public.ministries m where m.slug = 'capetown-khayelitsha'
union all
select m.id, 'Trauma debrief facilitator', 'expertise', 'soon', 2, 'trauma', true, '3 hrs/fortnight', array['Trauma debriefing']::text[], 'For our own team. Seventeen staff, all local, all carrying the same neighbourhood''s week.', '2026-08-07'::date, 'live' from public.ministries m where m.slug = 'capetown-khayelitsha'
union all
select m.id, 'Rebuild site foreman', 'expertise', 'urgent', 1, 'shelter', false, 'full time · 9 months', array['Site management', 'Arabic']::text[], 'One person to run four simultaneous household rebuilds, so our engineer can stop running them.', '2026-08-25'::date, 'live' from public.ministries m where m.slug = 'beirut-karantina'
union all
select m.id, 'Window glazing supplies', 'supplies', 'soon', 0, 'shelter', false, '90 windows', '{}', 'Glass and frames for ninety windows still boarded since the blast, in the quarter closest to the port.', '2026-07-24'::date, 'live' from public.ministries m where m.slug = 'beirut-karantina'
union all
select m.id, 'Russian-Kyrgyz youth leaders', 'volunteers', 'soon', 5, 'children', false, '2 evenings/week · 1 year', array['Kyrgyz', 'Russian']::text[], 'The youth room is open six evenings and staffed for two. Both languages, because the settlement is both.', '2026-08-14'::date, 'live' from public.ministries m where m.slug = 'bishkek-novostroyka'
union all
select m.id, 'Winter coal fund', 'funding', 'soon', 0, 'shelter', false, 'seasonal', '{}', 'Coal for sixty households before the first hard frost. Buying in September rather than December halves the price.', '2026-08-02'::date, 'live' from public.ministries m where m.slug = 'bishkek-novostroyka'
union all
select m.id, 'Newcomer welcome hosts', 'volunteers', 'ongoing', 16, 'refugees', false, '1 evening/week', array['English', 'Cooking']::text[], 'The table runs on sixteen people and currently has nine. Cooking, driving, and sitting next to someone new.', '2026-07-16'::date, 'live' from public.ministries m where m.slug = 'toronto-newcomer'
union all
select m.id, 'Immigration lawyer (pro bono)', 'expertise', 'soon', 1, 'refugees', true, '4 hrs/month', array['Immigration law']::text[], 'Claim reviews before filing. One evening a month at the table, or a call, whichever you can hold.', '2026-08-11'::date, 'live' from public.ministries m where m.slug = 'toronto-newcomer'
;

commit;

-- What you should see:
--   select count(*) from public.ministries;                     -- 32
--   select count(*) from public.needs where status = 'live';    -- 65
