/**
 * Writes supabase/seed_ph.sql: real needs posted on the web by churches and
 * ministries in the Philippines, gathered into tools/ph_needs.json.
 *
 *   node tools/build_ph_seed.mjs
 *   npx supabase@latest db query --linked -f supabase/seed_ph.sql
 *
 * Unlike the world sample this is REAL data, paraphrased from public pages:
 * every need ends with the page it came from, and contacts are only ones the
 * ministry publishes itself. The ministries have not signed up — the rows hang
 * off the sample owner, like the rest of the seed.
 *
 * Only rows whose slug starts "ph-" are its own, so re-running replaces this
 * set and leaves everything else alone. To remove it:
 *
 *   delete from public.ministries where slug like 'ph-%';
 */
import { readFileSync, writeFileSync } from "node:fs";

const { ministries: MINISTRIES, needs: NEEDS } = JSON.parse(
  readFileSync(new URL("./ph_needs.json", import.meta.url), "utf8"),
);

const OWNER = `(select id from auth.users where email = 'demo@example.org')`;

const q = (v) => (v === null || v === undefined || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => (v === null || v === undefined || v === "" ? "null" : Number(v));
const bool = (v) => (v ? "true" : "false");
const arr = (v) => (!v || !v.length ? "'{}'" : `array[${v.map((x) => q(x)).join(", ")}]::text[]`);

const detail = (n) => `${n.detail.trim()}\n\nSource: ${n.source_url}`;

const lines = [];
const w = (s = "") => lines.push(s);

w(`-- Terra — real needs from churches and ministries in the Philippines. Generated by tools/build_ph_seed.mjs; do not edit by hand.`);
w(`-- ${MINISTRIES.length} ministries and ${NEEDS.length} needs, each citing its source page.`);
w(`-- Safe to re-run: it replaces only its own rows (slug like 'ph-%').`);
w();
w(`begin;`);
w();
w(`delete from public.ministries where slug like 'ph-%' and owner_id = ${OWNER};`);
w();
w(`insert into public.ministries`);
w(`  (owner_id, slug, name, city, country, lat, lon, region, focus, since, staff, languages, contact, website, blurb)`);
w(`values`);
w(
  MINISTRIES.map(
    (m) =>
      `  (${OWNER}, ${q(m.slug)}, ${q(m.name)}, ${q(m.city)}, 'Philippines', ${num(m.lat)}, ${num(m.lon)}, 'asia', ` +
      `${arr(m.focus)}, ${num(m.since)}, ${num(m.staff)}, ${arr(m.languages)}, ${q(m.contact)}, ${q(m.website)}, ${q(m.blurb)})`,
  ).join(",\n") + ";",
);
w();
w(`insert into public.needs`);
w(`  (ministry_id, title, type, urgency, people, focus, remote, commitment, skills, detail, posted, status)`);
w(`select m.id, v.title, v.type, v.urgency, v.people, v.focus, v.remote, v.commitment, v.skills, v.detail, v.posted::date, 'live'`);
w(`from (values`);
w(
  NEEDS.map(
    (n) =>
      `  (${q(n.ministry)}, ${q(n.title)}, ${q(n.type)}, ${q(n.urgency)}, ${num(n.people) || 0}, ${q(n.focus)}, ${bool(n.remote)}, ` +
      `${q(n.commitment)}, ${arr(n.skills)}, ${q(detail(n))}, ${q(n.posted)})`,
  ).join(",\n"),
);
w(`) as v(slug, title, type, urgency, people, focus, remote, commitment, skills, detail, posted)`);
w(`join public.ministries m on m.slug = v.slug;`);
w();
w(`commit;`);

writeFileSync(new URL("../supabase/seed_ph.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`supabase/seed_ph.sql — ${MINISTRIES.length} ministries, ${NEEDS.length} needs`);
