/**
 * Writes supabase/seed.sql from the same fictional set the ?demo page uses, so
 * the two can never drift: the live globe and the demo globe show the same
 * thirty-two ministries and sixty-five needs.
 *
 *   node tools/build_seed.mjs
 *
 * Why a SQL file rather than a script that inserts over the network: `needs`
 * has no insert policy at all (see the comment in the migration — inserting is
 * the one thing the browser must not be able to do, because that is how you
 * would skip moderation). The anon key therefore cannot write this data, and
 * the two things that can are the service-role key and the SQL editor. The SQL
 * editor needs no secret to leave the machine, so that is what this targets.
 */
import { writeFileSync } from "node:fs";
import { MINISTRIES } from "../src/data/ministries.js";
import { NEEDS } from "../src/data/needs.js";

/** A fixed uuid, so re-running replaces this seed rather than duplicating it. */
const OWNER = "00000000-0000-4000-8000-00000000d3m0";
const EMAIL = "demo@example.org";

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => (v === null || v === undefined || v === "" ? "null" : Number(v));
const bool = (v) => (v ? "true" : "false");
const arr = (v) =>
  !v || !v.length ? "'{}'" : `array[${v.map((x) => q(x)).join(", ")}]::text[]`;

const lines = [];
const w = (s = "") => lines.push(s);

w(`-- Terra — demo seed. Generated by tools/build_seed.mjs; do not edit by hand.`);
w(`--`);
w(`-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query →`);
w(`-- paste → Run), the same way the schema migration was applied. The editor`);
w(`-- runs as a privileged role, which is what makes it able to write \`needs\`:`);
w(`-- that table deliberately has no insert policy, so neither the anon key nor`);
w(`-- a signed-in user can add rows. Only the service role and the SQL editor.`);
w(`--`);
w(`-- Safe to re-run. Everything below is owned by one fixed demo user, and the`);
w(`-- script clears that user's rows before inserting, so you get the same 32`);
w(`-- ministries and 65 needs every time rather than a second copy of them.`);
w(`--`);
w(`-- ALL OF THIS DATA IS FICTIONAL. Every organisation, person and need is`);
w(`-- invented, and every contact address is on example.org, which cannot`);
w(`-- receive mail. To remove it again:`);
w(`--`);
w(`--   delete from auth.users where id = '${OWNER}';`);
w(`--`);
w(`-- which cascades to the profile, the ministries and their needs.`);
w();
w(`begin;`);
w();
w(`-- ---------------------------------------------------------- demo owner`);
w(`--`);
w(`-- ministries.owner_id is not null and references profiles(id), which`);
w(`-- references auth.users(id) — so the seed needs a user to hang off. It has`);
w(`-- no password at all: the column is nullable (OAuth users carry none), and a`);
w(`-- null there means no credential can ever match, which is what you want of`);
w(`-- an account that exists only to own rows. Writing a hash instead would have`);
w(`-- pulled in pgcrypto's crypt() for no benefit. The on_auth_user_created`);
w(`-- trigger writes the matching profile.`);
w(`insert into auth.users (`);
w(`  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,`);
w(`  created_at, updated_at, raw_app_meta_data, raw_user_meta_data,`);
w(`  confirmation_token, recovery_token, email_change_token_new, email_change`);
w(`)`);
w(`values (`);
w(`  '00000000-0000-0000-0000-000000000000', '${OWNER}', 'authenticated', 'authenticated',`);
w(`  ${q(EMAIL)}, null, now(),`);
w(`  now(), now(), '{"provider":"email","providers":["email"]}'::jsonb,`);
w(`  '{"full_name":"Terra demo data","role":"ministry"}'::jsonb,`);
w(`  '', '', '', ''`);
w(`)`);
w(`on conflict (id) do nothing;`);
w();
w(`-- The trigger covers a fresh insert; this covers a database where the user`);
w(`-- already exists but the profile was removed.`);
w(`insert into public.profiles (id, full_name, role)`);
w(`values ('${OWNER}', 'Terra demo data', 'ministry')`);
w(`on conflict (id) do update set role = 'ministry';`);
w();
w(`-- Clear this owner's previous seed. Needs cascade from ministries.`);
w(`delete from public.ministries where owner_id = '${OWNER}';`);
w();
w(`-- ---------------------------------------------------------- ministries`);
w(`insert into public.ministries`);
w(`  (owner_id, slug, name, city, country, lat, lon, region, focus, since, staff, languages, contact, blurb)`);
w(`values`);
const mRows = MINISTRIES.map(
  (m) =>
    `  ('${OWNER}', ${q(m.id)}, ${q(m.name)}, ${q(m.city)}, ${q(m.country)}, ${num(m.lat)}, ${num(m.lon)}, ` +
    `${q(m.region)}, ${arr(m.focus)}, ${num(m.since)}, ${num(m.staff)}, ${arr(m.languages)}, ${q(m.contact)}, ${q(m.blurb)})`,
);
w(mRows.join(",\n"));
w(`on conflict (slug) do update set`);
w(`  owner_id = excluded.owner_id, name = excluded.name, city = excluded.city,`);
w(`  country = excluded.country, lat = excluded.lat, lon = excluded.lon,`);
w(`  region = excluded.region, focus = excluded.focus, since = excluded.since,`);
w(`  staff = excluded.staff, languages = excluded.languages,`);
w(`  contact = excluded.contact, blurb = excluded.blurb;`);
w();
w(`-- --------------------------------------------------------------- needs`);
w(`--`);
w(`-- status 'live' explicitly: the column defaults to pending_review so that`);
w(`-- anything reaching the table without passing moderation stays invisible,`);
w(`-- and only live rows are readable by the public policy. Seed data has no`);
w(`-- moderation pass to go through, so it is marked live here.`);
w(`--`);
w(`-- Joined on slug rather than carrying ministry uuids, so the ids stay`);
w(`-- whatever Postgres generated and this file has no machine state in it.`);
w(`insert into public.needs`);
w(`  (ministry_id, title, type, urgency, people, focus, remote, commitment, skills, detail, posted, status)`);
const nRows = NEEDS.map((n) => {
  const vals =
    `${q(n.title)}, ${q(n.type)}, ${q(n.urgency)}, ${num(n.people) || 0}, ${q(n.focus)}, ${bool(n.remote)}, ` +
    `${q(n.commitment)}, ${arr(n.skills)}, ${q(n.detail)}, ${q(n.posted)}::date, 'live'`;
  return `select m.id, ${vals} from public.ministries m where m.slug = ${q(n.ministry)}`;
});
w(nRows.join("\nunion all\n"));
w(`;`);
w();
w(`commit;`);
w();
w(`-- What you should see:`);
w(`--   select count(*) from public.ministries;                     -- ${MINISTRIES.length}`);
w(`--   select count(*) from public.needs where status = 'live';    -- ${NEEDS.length}`);

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");

const people = NEEDS.reduce((a, n) => a + (n.people || 0), 0);
const urgent = NEEDS.filter((n) => n.urgency === "urgent").length;
console.log(
  `supabase/seed.sql — ${MINISTRIES.length} ministries, ${NEEDS.length} needs ` +
    `(${urgent} urgent, ${people} people wanted)`,
);
