/**
 * Writes supabase/seed_world.sql: the world-wide sample (tools/world_sample.mjs)
 * on top of the hand-written seed, for about a thousand open needs in all.
 *
 *   node tools/build_world_seed.mjs
 *   npx supabase@latest db query --linked -f supabase/seed_world.sql
 *
 * It adds to the database rather than replacing it: only rows whose slug
 * starts "w-" are its own, so re-running it replaces the world sample and
 * leaves the hand-written ministries — and anything people have done against
 * them, applications and calls — alone. It assumes supabase/seed.sql has run
 * (it hangs off the same owner).
 *
 * ALL OF THIS DATA IS FICTIONAL; contacts are on example.org. To remove it:
 *
 *   delete from public.ministries where slug like 'w-%';
 */
import { writeFileSync } from "node:fs";
import { WORLD_MINISTRIES, WORLD_NEEDS } from "./world_sample.mjs";

/**
 * The sample owner, found by its address: the id in seed.sql is not a valid
 * uuid, so the live database's owner was created with a generated one.
 */
const OWNER = `(select id from auth.users where email = 'demo@example.org')`;

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => (v === null || v === undefined || v === "" ? "null" : Number(v));
const bool = (v) => (v ? "true" : "false");
const arr = (v) => (!v || !v.length ? "'{}'" : `array[${v.map((x) => q(x)).join(", ")}]::text[]`);

const lines = [];
const w = (s = "") => lines.push(s);

w(`-- Terra — the world-wide sample. Generated by tools/build_world_seed.mjs; do not edit by hand.`);
w(`-- ${WORLD_MINISTRIES.length} fictional ministries and ${WORLD_NEEDS.length} needs, added to the hand-written seed.`);
w(`-- Safe to re-run: it replaces only its own rows (slug like 'w-%').`);
w();
w(`begin;`);
w();
w(`delete from public.ministries where slug like 'w-%' and owner_id = ${OWNER};`);
w();
w(`insert into public.ministries`);
w(`  (owner_id, slug, name, city, country, lat, lon, region, focus, since, staff, languages, contact, blurb)`);
w(`values`);
w(
  WORLD_MINISTRIES.map(
    (m) =>
      `  (${OWNER}, ${q(m.id)}, ${q(m.name)}, ${q(m.city)}, ${q(m.country)}, ${num(m.lat)}, ${num(m.lon)}, ` +
      `${q(m.region)}, ${arr(m.focus)}, ${num(m.since)}, ${num(m.staff)}, ${arr(m.languages)}, ${q(m.contact)}, ${q(m.blurb)})`,
  ).join(",\n") + ";",
);
w();
w(`insert into public.needs`);
w(`  (ministry_id, title, type, urgency, people, focus, remote, commitment, skills, detail, posted, status)`);
w(`select m.id, v.title, v.type, v.urgency, v.people, v.focus, v.remote, v.commitment, v.skills, v.detail, v.posted::date, 'live'`);
w(`from (values`);
w(
  WORLD_NEEDS.map(
    (n) =>
      `  (${q(n.ministry)}, ${q(n.title)}, ${q(n.type)}, ${q(n.urgency)}, ${num(n.people) || 0}, ${q(n.focus)}, ${bool(n.remote)}, ` +
      `${q(n.commitment)}, ${arr(n.skills)}, ${q(n.detail)}, ${q(n.posted)})`,
  ).join(",\n"),
);
w(`) as v(slug, title, type, urgency, people, focus, remote, commitment, skills, detail, posted)`);
w(`join public.ministries m on m.slug = v.slug;`);
w();
w(`commit;`);

writeFileSync(new URL("../supabase/seed_world.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`supabase/seed_world.sql — ${WORLD_MINISTRIES.length} ministries, ${WORLD_NEEDS.length} needs`);
